image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - deploy

npm_ci:
  stage: prepare
  script:
    - npm ci

test_mocha:
  stage: test
  script:
    - npm run test

test_lint:
  stage: test
  script:
    - npm run lint

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
